

services:
  server:
    build:
      context: .
    environment:
      PORT: 4000
      DB_NAME: "servic-user"
      DB_HOST: "127.0.0.1" 
      DB_PORT: 27017 
      NODE_ENV: production
    ports:
      - 4000:4000

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017


